### ISSUE TITLE
OPERA-SDSVnV-13_2:Functional validation of the PGE for L2_RTC_S1 products

### ISSUE THREAD

**Issue by oddes** [nasa/opera-sds-int#29]
While testing noted multiple issues with the runconfig file:

1. I do not find the location to update:
landcover_file: input_dir/*TBD*.tif
worldcover_file: input_dir/*TBD*.tif

2.  I have executed script with ignoring those options. getting the following errors:

hysdsops@opera-int-mozart-pop1:~/mozart/ops/opera-pcm/tools/OPERA-SDSVnV-13_2$ docker run --rm -u $UID:$(id -g) -v ${WORKING_DIR}/expected_output_dir:/home/conda/expected_output_dir:ro -v ${WORKING_DIR}/runconfig:/home/conda/runconfig:ro -v ${WORKING_DIR}/input_dir:/home/conda/input_dir:ro -v ${WORKING_DIR}/output_dir:/home/conda/output_dir -i --tty opera_pge/rtc_s1:2.0.0-er.5.0 --file /home/conda/runconfig/rtc_s1_sample_runconfig-v2.0.0-er.5.0.yaml
Running preprocessor for RtcS1PreProcessorMixin
Traceback (most recent call last):
  File "/home/rtc_user/opera/pge/base/base_pge.py", line 96, in _validate_runconfig
    self.runconfig.validate()
  File "/home/rtc_user/opera/pge/base/runconfig.py", line 142, in validate
    yamale.validate(pge_schema, runconfig_data, strict=strict_mode)
  File "/home/rtc_user/miniconda3/lib/python3.9/site-packages/yamale/yamale.py", line 43, in validate
    raise YamaleError(results)
yamale.yamale_error.YamaleError: Error validating data '/home/conda/runconfig/rtc_s1_sample_runconfig-v2.0.0-er.5.0.yaml' with schema '/home/rtc_user/opera/pge/base/schema/base_pge_schema.yaml'
	RunConfig.Groups.SAS.runconfig.groups.input_file_group.burst_id: Length of [] is less than 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rtc_user/opera/scripts/pge_main.py", line 187, in <module>
    pge_main()
  File "/home/rtc_user/opera/scripts/pge_main.py", line 183, in pge_main
    pge_start(run_config_filename)
  File "/home/rtc_user/opera/scripts/pge_main.py", line 157, in pge_start
    pge.run()
  File "/home/rtc_user/opera/pge/base/base_pge.py", line 740, in run
    self.run_preprocessor(**kwargs)
  File "/home/rtc_user/opera/pge/rtc_s1/rtc_s1_pge.py", line 56, in run_preprocessor
    super().run_preprocessor(**kwargs)
  File "/home/rtc_user/opera/pge/base/base_pge.py", line 179, in run_preprocessor
    self._validate_runconfig()
  File "/home/rtc_user/opera/pge/base/base_pge.py", line 105, in _validate_runconfig
    self.logger.critical(
  File "/home/rtc_user/opera/util/logger.py", line 407, in critical
    raise RuntimeError(description)
RuntimeError: Validation of RunConfig file /home/conda/runconfig/rtc_s1_sample_runconfig-v2.0.0-er.5.0.yaml failed, reason(s): 
Error validating data '/home/conda/runconfig/rtc_s1_sample_runconfig-v2.0.0-er.5.0.yaml' with schema '/home/rtc_user/opera/pge/base/schema/base_pge_schema.yaml'
	RunConfig.Groups.SAS.runconfig.groups.input_file_group.burst_id: Length of [] is less than 1
hysdsops@opera-int-mozart-pop1:~/mozart/ops/opera-pcm/tools/OPERA-SDSVnV-13_2$ 

Please see the ticket for details:
https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3996156&group_by=cases:title&group_order=asc&group_id=-1

**Comment by collinss-jpl** [comment]
The Testrail procedure for RTC-S1 has been updated to address these issues: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3996156
